# roles/tasks/main.yml
---
- name: Install packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - httpd
    #- mod_ssl
    - firewalld

#- name: Enabled mod_rewrite
#  apache2_module:
#    name: rewrite
#    state: present
#  notify:
#    - restart httpd

- name: Ensure Apache is always running
  service:
    name: httpd
    state: started
    enabled: yes

- name: Install main configuration file
  template:
    src: httpd.conf.j2
    dest: "{{ httpd_config }}"
    owner: "{{ httpd_user }}"
    mode: 0644
    setype: httpd_config_t
  notify: restart httpd

#- name: Install mod_ssl configuration file
#  template:
#    src: ssl.conf.j2
#    dest: "{{ httpd_ssl_config }}"
#    owner: "{{ httpd_user }}"
#    mode: 0644
#    setype: httpd_config_t
#  notify: restart httpd

- name: Copying html index file
  copy:
    src: index.html
    dest: /var/www/html/
  notify: restart httpd
    
- name: Enable firewalld
  service:
    name: firewalld 
    state: started
    enabled: yes

- name: Enable httpd on port 80
  firewalld:
    zone: internal
    port: 80/tcp
    permanent: true
    state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted